name: Run tests

on:
  workflow_dispatch:
  push:
    branches:
      - solutions
  pull_request:
    branches:
      - solutions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Set up Ubuntu
        run: sudo apt-get update

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven

      - name: Test
        run: mvn --batch-mode --update-snapshots verify
  